---
title: "AMNH Parasite Biodiversity Analysis"
author: "Maureen Anne Williams"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Input the data and get required R packages
```{r warning=FALSE, tidy=TRUE}
#Load the tidyverse package
library(tidyverse)
library(plyr)
library(knitr)
#Input dataset from csv
mastersheet<-read.csv("mastersheet.csv", header=T, stringsAsFactors = F)

#Modify spreadsheet so all numbers are in longform
library(reshape2)
form_master<- melt(mastersheet, 
                     variable.name = "key",
                     value.names = "value",
                     id.vars = c("fish_id", "fish_species", "island"),
                    measure.vars = c("trematodes_count", "cestodes_count",
                                     "copepods_count", "isopods_count", 
                                     "nematodes_count", "monogenians_count",
                                     "gnathopods_count"))

form_master$transmission[form_master$key=="trematodes_count"] <- "trophic" 
form_master$transmission[form_master$key=="cestodes_count"] <- "trophic" 
form_master$transmission[form_master$key=="copepods_count"] <- "direct" 
form_master$transmission[form_master$key=="isopods_count"] <- "direct" 
form_master$transmission[form_master$key=="nematodes_count"] <- "trophic"
form_master$transmission[form_master$key=="monogenians_count"] <- "direct" 
form_master$transmission[form_master$key=="gnathopods_count"] <- "direct" 




#Generate a list of all host species
splist<-c("acanig", "cepuro", "chrmar", "pararc", "psebar", "steaur")
```

###Find means and standard deviations for first species
####We've loaded in the data and we have a list of all the species.We then want to find the mean and standard error of parasite abundance for each species. 
```{r warning=FALSE, tidy=TRUE}
kable(summary_table <- mastersheet %>%
  ddply(c("fish_species", "fishing_status"), summarise,
                    N    = length(fish_species),
                    tre_mean = mean (trematodes_count,na.rm=T),
                    tre_sd   = sd(trematodes_count,na.rm=T),
                    tre_se   = tre_sd / sqrt(N),
                    cest_mean = mean (cestodes_count,na.rm=T),
                    cest_sd   = sd(cestodes_count,na.rm=T),
                    cest_se   = cest_sd / sqrt(N),
                    cop_mean = mean (copepods_count,na.rm=T),
                    cop_sd   = sd(copepods_count,na.rm=T),
                    cop_se   = cop_sd / sqrt(N),
                    iso_mean = mean (isopods_count,na.rm=T),
                    iso_sd   = sd(isopods_count,na.rm=T),
                    iso_se   = iso_sd / sqrt(N),
                    mono_mean = mean (monogenians_count,na.rm=T),
                    mono_sd   = sd(monogenians_count,na.rm=T),
                    mono_se   = mono_sd / sqrt(N),
                    nem_mean = mean (nematodes_count,na.rm=T),
                    nem_sd   = sd(nematodes_count,na.rm=T),
                    nem_se   = nem_sd / sqrt(N),
                    gna_mean = mean (gnathopods_count,na.rm=T),
                    gna_sd   = sd(gnathopods_count,na.rm=T),
                    gna_se   = gna_sd / sqrt(N)))
```


Plot the data
```{r}
bitetime_plot<-ggplot(bite_summary, aes(x=temp, y=mean, color=trial)) + 
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.3) +
  geom_point(size=3)+
  xlab("Temperature ?C")+
  ylab("Bite Time (s)")+
  scale_colour_manual(values=c("orange","darkgray"),
                      name  ="Infection Status",
                      breaks=c("I", "U"),
                      labels=c("Infected", "Uninfected")) +
  scale_shape_discrete(name  ="Prey Status",
                       breaks=c("dead", "live"),
                       labels=c("Dead", "Live"))+
  theme(panel.grid.major = element_blank(), legend.position="none", panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
```

